### ISSUE TITLE
[DISCUSSION] Help wanted for false-positive Anti Virus flags

### ISSUE THREAD

**Issue by louis-e** [louis-e/arnis#292]
Hi there! I was recently made aware that Arnis v2.1.3 is falsely tagged as malicious by a few anti virus programs (https://www.virustotal.com/gui/file/a2f8ad419ce27d3109e9f955cc26c6131f6b70f2946bdb93119170fc6af3b82d). This did not happen for Arnis v2.1.2 (https://www.virustotal.com/gui/file/34e3e6cd0c5e7ecae2c10d42fa71a90e059251e7a127e120d03c52c18187b1d2).

I'd be really grateful for some people with expertise in that area to help me analyzing what could cause these false-positive flags, possibly by reading through the code after looking at the version changelog and inspecting the virustotal results. Also I'm planning to look into signing the build with a certificate (self signed though) if that also helps. Maybe there are some Github Actions solutions out there for doing exactly that.

**Comment by ErrorLoadingUsername** [comment]
have you asked ChatGPT yet?

> To analyze and resolve the false-positive issue for Arnis v2.1.3 and improve your software's reputation with antivirus programs, here’s a step-by-step guide:

---

### **1. Analyze VirusTotal Results**
1. **Review Detection Details**:
   - Compare the VirusTotal reports for **v2.1.3** and **v2.1.2**.
   - Look at specific antivirus engines that flagged v2.1.3 as malicious. Common triggers:
     - Obfuscated code.
     - Suspicious network activity.
     - Bundled third-party libraries.

2. **Identify Common Patterns**:
   - Check the file differences between versions.
   - Identify any new libraries or major changes introduced in **v2.1.3**.

---

### **2. Compare Code Changes**
1. **Review the Changelog**:
   - What significant changes were made between **v2.1.2** and **v2.1.3**?
   - Focus on:
     - Added dependencies or libraries.
     - Changes in file handling, encryption, or obfuscation.
     - Network requests or external calls.

2. **Run a Diff Tool**:
   - Use tools like `diff`, `Beyond Compare`, or `Meld` to compare the source code of both versions.

---

### **3. Debug Potential Issues**
1. **Check for False-Positive Triggers**:
   - **Compression or Packing**: If you’re using tools like UPX, antivirus programs might flag it.
   - **Network Requests**: New external calls could appear suspicious.
   - **Executable Metadata**: Incomplete or absent metadata (e.g., publisher, version) increases suspicion.
   - **Unused Code**: Leftover or experimental code can also trigger warnings.

2. **Test Locally**:
   - Run static analysis tools like [[ClamAV](https://www.clamav.net/)](https://www.clamav.net/) or [[Malwarebytes](https://www.malwarebytes.com/)](https://www.malwarebytes.com/) to detect suspicious patterns.
   - Use [[PEStudio](https://winitor.com/)](https://winitor.com/) to analyze the binary for unusual attributes.

---

### **4. Sign the Executable**
1. **Generate a Self-Signed Certificate**:
   - Use a tool like `openssl` or `signtool.exe` to create a self-signed certificate:
     ```bash
     openssl req -new -x509 -keyout mycert.key -out mycert.crt -days 365
     ```
   - Package the certificate with your build process.

2. **Sign the Executable**:
   - On Windows, use `signtool` to sign your executable:
     ```bash
     signtool sign /f mycert.pfx /p password /t http://timestamp.digicert.com your_app.exe
     ```
   - On Linux, use `osslsigncode`.

3. **Consider a Trusted Certificate Authority (CA)**:
   - While self-signing helps, purchasing a code-signing certificate from a trusted CA (e.g., DigiCert, Sectigo) will drastically reduce false positives.

---

### **5. Automate via GitHub Actions**
1. **Setup GitHub Workflow**:
   - Create a `.yml` file in `.github/workflows/`:
     ```yaml
     name: Build and Sign
     on:
       push:
         branches:
           - main
     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
           - name: Build Executable
             run: make build
           - name: Sign Executable
             run: |
               openssl req -new -x509 -keyout key.pem -out cert.pem -days 365
               osslsigncode sign -certs cert.pem -key key.pem -in your_app.exe -out your_app_signed.exe
           - name: Upload Artifact
             uses: actions/upload-artifact@v2
             with:
               name: signed-executable
               path: your_app_signed.exe
     ```

---

### **6. Submit for Reanalysis**
1. **Contact Antivirus Vendors**:
   - Many vendors allow developers to submit files flagged as false positives for reanalysis:
     - [[Microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission)](https://www.microsoft.com/en-us/wdsi/filesubmission)
     - [[McAfee](https://www.mcafee.com/en-us/secure-home-programs/file-misrepresentation-form.html)](https://www.mcafee.com/en-us/secure-home-programs/file-misrepresentation-form.html)
     - [[Kaspersky](https://opentip.kaspersky.com/)](https://opentip.kaspersky.com/)
     - [[Others via VirusTotal](https://www.virustotal.com/)](https://www.virustotal.com/).

2. **Re-upload to VirusTotal**:
   - Once the executable is signed, re-upload it to VirusTotal. Signing significantly reduces false positives.

---

### **7. Best Practices for Future Releases**
1. **Improve Metadata**:
   - Add proper metadata to the executable, such as company name, product name, and version.

2. **Minimize Suspicious Features**:
   - Avoid unnecessary obfuscation or packing.
   - Use clear and readable code for critical functionalities.

3. **Test Builds Regularly**:
   - Run VirusTotal checks for each pre-release build.
   - Automate these checks using tools like `vt-cli`.

By following these steps, you can identify the root cause of the false positives, reduce future occurrences, and build user trust.
